# Generated by Django 4.1 on 2023-12-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_project', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('due_date', models.DateField(null=True)),
                ('priority', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('priority', models.PositiveBigIntegerField(default=1)),
                ('due_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_task_app.project', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
