# Generated by Django 4.1 on 2023-12-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_task_app.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_task',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
